version: '2.3'

services:
  gem:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app:delegated
      # for purposes of release
      - $HOME/.ssh:/root/.ssh
      - $HOME/.gitconfig:/root/.gitconfig
      - $HOME/.gem/credentials:/root/.gem/credentials
